### ISSUE TITLE
How did you write it?

### ISSUE THREAD

**Issue by 0xj0hn** [bxhh7/vio10#1]
The thing is how you wrote it? It seems unnatural that the kernel.asm file contains hundreds of lines of assembly code.
How is it possible to write something like this? I want to learn more about it XD
HOW DID YOU WRITE HUNDREDS OF LINES THERE? Your brain should be blazingly powerful ~:)

**Comment by bxhh7** [comment]
the kernel.asm file is actually compiler-generated, used solely for debugging purposes. it's the assembly equivalent of kernel.c.

**Comment by bxhh7** [comment]
> The thing is how you wrote it? It seems unnatural that the kernel.asm file contains hundreds of lines of assembly code. How is it possible to write something like this? I want to learn more about it XD HOW DID YOU WRITE HUNDREDS OF LINES THERE? Your brain should be blazingly powerful ~:)


the kernel.asm file is actually compiler-generated, used solely for debugging purposes.

**Comment by 0xj0hn** [comment]
Uhum. Thanks for the information.
